steps:
  # create a tag in the build environment so that versioneer can find it
  - name: "gcr.io/cloud-builders/git"
    args: ["tag", "$TAG_NAME"]
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/andrewross.dev:$TAG_NAME"
      - "."
    timeout: 600s
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/andrewross.dev:$TAG_NAME"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "andrewrosss-dev"
      - "--image"
      - "gcr.io/$PROJECT_ID/andrewross.dev:$TAG_NAME"
      - "--region"
      - "us-east1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
timeout: 660s
tags: ["latest", "$TAG_NAME", $SHORT_SHA, $BUILD_ID]
images: ["gcr.io/$PROJECT_ID/andrewross.dev"]
