steps:
# Clone source code
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/andrewrosss/andrewrosss.dev.git']
  timeout: 600s
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/andrewross.dev:$TAG_NAME.$SHORT_SHA', '.']
  dir: 'andrewrosss.dev'
  timeout: 600s
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/andrewross.dev:$TAG_NAME.$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'andrewrosss-dev', '--image', 'gcr.io/$PROJECT_ID/andrewross.dev:$TAG_NAME.$SHORT_SHA', '--region', 'us-east1', '--platform', 'managed', '--allow-unauthenticated']
options:
    machineType: 'N1_STANDARD_1'
timeout: 660s
tags: ['latest', '$TAG_NAME.$SHORT_SHA']
images: ['gcr.io/$PROJECT_ID/andrewross.dev']